### ISSUE TITLE
Auto slack uploader fails

### ISSUE THREAD

**Issue by Darth-Arminius** [jmhobbs/cultofthepartyparrot.com#284]
Not sure if this has already been mentioned, already known or if it is specifically a problem with emojipacks (it probably is but I felt it was worth mentioning it here).

I followed the instructions to start the auto upload:

First I ran `yarn install`.

Then `yarn build` which initially had test failure problems but that seems to have been fixed.

Then I ran `emojipacks`.
I entered my slack details and the absolute path to the `parrotparty.yaml` file.

Then I get this error:

```Starting import
Got tokens
Logged in
Uh oh! Error: Login error: could not get emoji upload crumb for https://[my-subdomain].slack.com
(node:11208) UnhandledPromiseRejectionWarning: Error: Login error: could not get emoji upload crumb for https://[my-subdomain].slack.com
    at Slack.emoji ([my-path]\npm\node_modules\emojipacks\lib\slack.js:162:34)
    at Slack.emoji.next (<anonymous>)
    at onFulfilled ([my-path]\\npm\node_modules\emojipacks\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
This most probably has something to do with emojipacks and it seems many people have voiced their errors [there](https://github.com/lambtron/emojipacks/issues) too. It seems that what [this issue](https://github.com/lambtron/emojipacks/issues/158) is about is the most likely culprit. Not sure if/when that will be fixed or how long.

So I guess this is more of a notification to anyone wanting to run the auto uploader that it may not currently be working. Are there any alternatives we could look into in the meantime or even as a permanent solution/replacement?

**Comment by jmhobbs** [comment]
Yeah, looks like an emojipacks issue to me.  I'm up for a warning in the README.  Slack has no API for uploading emoji, only listing them, so there's not really a better option except for browser automation/emulation.  I'm open to ideas though!

**Comment by Darth-Arminius** [comment]
Ah, well that's a great shame. I'll have a little look into it and see what our alternatives could be. I agree that in the meantime a warning in the README would be good idea.

**Comment by Darth-Arminius** [comment]
Looking through, it seems most (if not all) batch slack emoji auto uploaders are broken as of Slack's latest update to the emoji uploading/managing UI. However, I did find a working chrome extension that allows for a slightly more manual way of batch uploading emojis. You drag and drop all the emoji files into this extension's UI and it will batch upload them all automatically. Extension can be found here: https://chrome.google.com/webstore/detail/neutral-face-emoji-tools/anchoacphlfbdomdlomnbbfhcmcdmjej

**Comment by jmhobbs** [comment]
Looks good to me, mind adding a quick PR with a warning and a link to the Chrome extension?
